services:

  app:

    build: .

    container_name: quote-api

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - /app/node_modules

    command: npm start

  tests:
    build: .
    command: npm test
    